/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/Nebula/Nebula.gltf -o src/components/Nebula.jsx -r public 
Author: tamminen (https://sketchfab.com/tamminen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nebula-traveller-d209120c922b4a4aa06e7b77a840f851
Title: Nebula traveller
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Nebula({ hovered, ...props }) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/Nebula/Nebula.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['MorphBake'].reset().fadeIn(0.5).play()
    actions['MorphBake'].timeScale = hovered ? 10 : 1
    return () => actions['MorphBake'].reset().fadeOut(0.5)
  }, [hovered])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sphere_0" rotation={[Math.PI / 2, 0, 0]}>
                <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={materials['Scene_-_Root']} morphTargetDictionary={nodes.mesh_0.morphTargetDictionary} morphTargetInfluences={nodes.mesh_0.morphTargetInfluences} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Nebula/Nebula.gltf')
