/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/Staff/Staff.gltf -o src/components/Staff.jsx -r public 
Author: tamminen (https://sketchfab.com/tamminen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/staff-pick-6b62b46f5337400289281525b3949090
Title: "Staff pick"
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Staff({ hovered, ...props}) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/Staff/Staff.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['Animation'].reset().fadeIn(0.5).play();
    actions['Animation'].timeScale = hovered ? 3 : 1
    return () => {
      if (actions['Animation']) {
        actions['Animation'].reset().fadeOut(0.5)
      }
    }
  }, [hovered])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="inner_0">
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.material} />
              </group>
              <group name="outer_1">
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.outer} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Staff/Staff.gltf')
